Repository boostcamp-2020/Project07-A-RealTime-Seat-Reservation-System, pull requests merged in 2020-12, with the labels that each got.

#13 [J143]graphql api
  api-server/constants/index.ts
  api-server/models/booking.ts
  api-server/models/concert.ts
  api-server/models/index.ts
  api-server/models/item.ts
  api-server/models/place.ts
  api-server/models/schedule.ts
  api-server/models/user.ts
  api-server/package.json
  api-server/resolvers/booking.ts
  api-server/resolvers/index.ts
  api-server/resolvers/item.ts
  api-server/resolvers/schedule.ts
  api-server/resolvers/user.ts
  api-server/schemas/index.ts
  api-server/schemas/schema.graphql
  api-server/schemas/types.ts
  api-server/yarn.lock
Labels: BE

#16 [J143]feat: booking API
  api-server/models/booking.ts
  api-server/resolvers/booking.ts
  api-server/schemas/types.ts
Labels: BE

#17 [J133] SeatSelectionArea와 관련된 리팩토링 진행
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
  client/src/constants/seatStatus.ts
  client/src/modules/seats.ts
  client/src/styles/seatColor.ts
  client/src/types/seatInfo.ts
Labels: FE, Refactor

#19 [J143] socket event
  socket-server/app.ts
  socket-server/constants/index.ts
  socket-server/controllers/index.ts
  socket-server/db/redis.ts
Labels: BE

#22 [J106] 변경된 소켓 이벤트로 수정, 좌석선택페이지 잔여석 소켓 연결
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/components/SeatSelectionBox/SeatInfoArea/SeatInfoArea.tsx
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
  client/src/components/common/EmptySeatsCount/EmptySeatsCount.tsx
  client/src/reducers/seatReducer.ts
  client/src/stores/SeatStore.tsx
  client/src/types/seatInfo.ts
Labels: FE

#30 [J106] API와 연결하기
  .gitignore
  client/debug.log
  client/package.json
  client/src/App.tsx
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/components/ConcertDetails/CalendarPickerTmp/CalendarPicker.js
  client/src/components/ConcertDetails/ConcertDetails.tsx
  client/src/components/ContentsArea/ContentsArea.tsx
  client/src/components/ItemCardArea/ItemCard.tsx
  client/src/components/MainHeader/MainHeader.tsx
  client/src/components/SeatSelectionBox/SeatInfoArea/SeatInfoArea.tsx
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
  client/src/components/common/EmptySeatsCount/EmptySeatsCount.tsx
  client/src/constants/seatStatus.ts
  client/src/hooks/useConcertInfo.ts
  client/src/index.tsx
  client/src/modules/concertInfo.ts
  client/src/modules/seats.ts
  client/src/modules/socket.ts
  client/src/pages/SelectTime.tsx
  client/src/reducers/seatReducer.ts
  client/src/stores/SeatStore.tsx
  client/src/styles/seatColor.ts
  client/src/types/concertInfo.ts
  client/yarn.lock
Labels: FE

#31 [J143] Feat/filtering
  api-server/models/genre.ts
  api-server/models/index.ts
  api-server/models/item.ts
  api-server/resolvers/genre.ts
  api-server/resolvers/index.ts
  api-server/resolvers/item.ts
  api-server/schemas/types.ts
  client/src/components/ItemCardArea/ItemCardArea.tsx
  client/src/components/ItemFilterArea/ItemFilter.tsx
  client/src/components/ItemFilterArea/ItemFilterArea.tsx
  client/src/hooks/useItems.tsx
  client/src/modules/index.ts
  client/src/modules/items.ts
  client/src/pages/ItemList.tsx
  client/src/socket.ts
  socket-server/.eslintrc
  socket-server/app.ts
  socket-server/constants/index.ts
  socket-server/controllers/index.ts
  socket-server/namespaces/api-server.ts
  socket-server/namespaces/client.ts
  socket-server/namespaces/index.ts
Labels: BE, FE

#33 [J106] 회차선택 페이지에서 새로고침시 발생하는 문제 해결
  client/src/App.tsx
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/components/ContentsArea/ContentsArea.tsx
  client/src/components/ItemCardArea/ItemCard.tsx
  client/src/modules/concertInfo.ts
  client/src/pages/SeatSelection.tsx
  client/src/pages/SelectTime.tsx
  client/src/types/concertInfo.ts
Labels: FE

#36 [J106] 결제페이지 구현
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/components/ContentsArea/ContentsArea.tsx
  client/src/components/MainHeader/MainHeader.tsx
  client/src/components/PaymentSelectInfo/PaymentSelectInfo.tsx
  client/src/components/SeatSelectionBox/SeatInfoArea/SeatInfoArea.tsx
  client/src/components/SeatSelectionBox/SeatSelectionBox.tsx
  client/src/components/common/EmptySeatsCount/EmptySeatsCount.tsx
  client/src/components/common/StepButton/StepButton.tsx
  client/src/components/common/index.ts
  client/src/components/index.ts
  client/src/modules/concertInfo.ts
  client/src/pages/Payment.tsx
  client/src/styles/variables.ts
  client/src/types/concertInfo.ts
Labels: FE

#39 [J106] 예약 요청, 마이페이지 생성, 유저정보 저장
  api-server/schemas/types.ts
  client/src/App.tsx
  client/src/components/ContentsArea/ContentsArea.tsx
  client/src/components/ItemCardArea/ItemCard.tsx
  client/src/components/LoginArea/LoginArea.tsx
  client/src/components/MainHeader/MainHeader.tsx
  client/src/components/PaymentSelectInfo/PaymentSelectInfo.tsx
  client/src/components/SeatSelectionBox/SeatInfoArea/SeatInfoArea.tsx
  client/src/components/common/EmptySeatsCount/EmptySeatsCount.tsx
  client/src/components/common/StepButton/StepButton.tsx
  client/src/imgs/tmp.jpg
  client/src/index.css
  client/src/modules/seats.ts
  client/src/pages/ItemList.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Payment.tsx
  client/src/pages/index.tsx
Labels: FE

#43 [J106] 각종 버그 수정, 전역스토어 수정, 마이페이지 구현
  api-server/schemas/types.ts
  client/src/App.tsx
  client/src/components/BookingCancelArea/BookingCancelArea.tsx
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/components/ItemFilterArea/ItemFilter.tsx
  client/src/components/MyPageArea/MyPageArea.tsx
  client/src/components/PaymentSelectInfo/PaymentSelectInfo.tsx
  client/src/components/SeatSelectionBox/SeatInfoArea/SeatInfoArea.tsx
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
  client/src/components/common/EmptySeatsCount/EmptySeatsCount.tsx
  client/src/components/common/StepButton/StepButton.tsx
  client/src/components/index.ts
  client/src/modules/concertInfo.ts
  client/src/pages/BookingCancel.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Payment.tsx
  client/src/pages/SeatSelection.tsx
  client/src/pages/index.tsx
  client/src/styles/variables.ts
Labels: FE

#45 [J106] 마이페이지 수정
  client/src/components/MyPageArea/MyPageArea.tsx
Labels: FE

#46 [J106] 버그 수정, 예매취소페이지 구현, 상세정보탭 구현
  client/public/favicon.ico
  client/src/components/BookingCancelArea/BookingCancelArea.tsx
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/components/ConcertDetails/ConcertDetails.tsx
  client/src/components/ConcertDetails/InfoArea/InfoArea.tsx
  client/src/components/ContentsArea/ContentsArea.tsx
  client/src/components/ItemCardArea/ItemCard.tsx
  client/src/components/ItemCardArea/ItemCardArea.tsx
  client/src/components/MyPageArea/MyPageArea.tsx
  client/src/components/SeatSelectionBox/SeatInfoArea/SeatInfoArea.tsx
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
  client/src/components/common/EmptySeatsCount/EmptySeatsCount.tsx
  client/src/components/common/index.ts
  client/src/index.css
  client/src/modules/concertInfo.ts
  client/src/pages/BookingCancel.tsx
  client/src/pages/SelectTime.tsx
  client/src/types/booking.ts
Labels: FE

#50 [J106] 상세정보탭 완성, 캘린더 개선
  api-server/models/item.ts
  api-server/schemas/types.ts
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/components/ConcertDetails/InfoArea/InfoArea.tsx
  client/src/components/ContentsArea/ContentsArea.tsx
  client/src/components/PaymentSelectInfo/PaymentSelectInfo.tsx
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
  client/src/modules/concertInfo.ts
Labels: FE

#52 Feat: 좌석 선택 확대 축소할때 확대 축소 효과를 추가
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
Labels: FE

#51 [J106] 사용하지 않는 코드 제거
  .gitignore
  client/public/index.html
  client/src/components/ConcertDetails/ConcertDetails.tsx
  client/src/components/ConcertDetails/InfoArea/InfoArea.tsx
  client/src/components/ContentsArea/ContentsArea.tsx
  client/src/components/MyPageArea/MyPageArea.tsx
  client/src/components/PaymentSelectInfo/PaymentSelectInfo.tsx
  client/src/components/SeatSelectionBox/SeatInfoArea/SeatInfoArea.tsx
  client/src/components/SeatSelectionBox/SeatSelectionBox.tsx
  client/src/modules/concertInfo.ts
Labels: FE

#54 [J106] cancel페이지 url로 접근 못하도록 수정
  client/src/components/BookingCancelArea/BookingCancelArea.tsx
  client/src/components/MyPageArea/MyPageArea.tsx
  client/src/components/PaymentSelectInfo/PaymentSelectInfo.tsx
  client/src/components/SeatSelectionBox/SeatSelectionArea/SeatSelectionArea.tsx
  client/src/types/booking.ts
Labels: FE

#57 [J106] 로그인 안하면 좌석선택 불가하도록 수정
  client/src/components/BookingCancelArea/BookingCancelArea.tsx
  client/src/components/ConcertDetails/CalendarPicker/CalendarPicker.js
  client/src/pages/MyPage.tsx
Labels: FE
